### ISSUE TITLE
Is this expo compatible?

### ISSUE THREAD

**Issue by peteratdivvy** [amplitude/experiment-react-native-client#14]
Hi y'all, 

We are interested in using amplitude experiments in our Expo-managed application. I tried setting up this library and i'm getting the following errors: 
<img width="807" alt="image" src="https://user-images.githubusercontent.com/98723052/178805832-8bfca2f6-26a6-4832-bbc9-119bd670887e.png">

Is this compatible with Expo? I'm guessing not because you are using Native modules under the hood (though I see a PR open to try to avoid that).

Thanks!

**Comment by bgiori** [comment]
Hi @peteratdivvy, currently not compatible, but v1 with expo support will be coming out soon--likely in the next couple of weeks (same goes for Amplitude Analytics SDK).

**Comment by peteratdivvy** [comment]
hey @bgiori, we'd love to help test this out if you are looking for testers!

**Comment by bgiori** [comment]
@peteratdivvy that would be fantastic! I'll make sure to give you an update when the beta release comes out. 

Are you using Expo Go? We are still using native modules in the SDK. However, the use is strictly for persistence & pulling contextual information from the app & os, etc. 

Segment wrote up these limitations in their RN SDK which puts it succinctly:

![Screen Shot 2022-07-14 at 7 11 07 AM](https://user-images.githubusercontent.com/3282199/179003111-6fbf22e8-b835-4452-adf5-74d4d7245493.png)

**Comment by bgiori** [comment]
Hmmm, ok. I can probably work around that. The custom native modules are used to get more refined platform context, but not actually required to operate the SDK. React-native generally provides sufficient context and the native modules can be stubbed out. 

The beta versions of the Analytics + Experiment have been released:
* Experiment: https://www.docs.developers.amplitude.com/experiment/sdks/react-native-sdk/
* Analytics: https://www.docs.developers.amplitude.com/data/sdks/react-native-sdk/

**Comment by bgiori** [comment]
Creating github issues works well, or if you prefer email feel free to reach out to brian.giori@amplitude.com

**Comment by ajsmth** [comment]
Hey there - I'm looking at using this package as well and was curious about what state it's in. One of the more recent PRs seems to allude to the fact that it is no longer using the native runtime under the hood? I wanted to see if this is purely JS and compatible w/o needing packages like async storage
