### ISSUE TITLE
Experiment.variant() method does not return payload on Android

### ISSUE THREAD

**Issue by FerdyTarawan** [amplitude/experiment-react-native-client#7]
I ran into some problem while integrating this library. When an experiment / flag is using a payload and I called ```Experiment.variant()``` method, it only returns the value and not the payload. This only happens on Android, on IOS, it's working correctly.

Any ideas why this is happening?

Example Log on Android:
<img width="680" alt="Screen Shot 2021-12-09 at 10 45 05" src="https://user-images.githubusercontent.com/17270207/145510479-b0a1bca4-df75-4135-bf8a-ec1d8977bd90.png">

Example Log on IOS:

<img width="910" alt="Screen Shot 2021-12-09 at 10 25 40" src="https://user-images.githubusercontent.com/17270207/145510550-035ecbc3-2d37-4d08-88ec-fa5ca4f9dd7f.png">

**Comment by bgiori** [comment]
Sorry for the delay: fixed in #8

**Comment by bgiori** [comment]
@FerdyTarawan Thanks for reporting this. 

The new version, `0.5.2`, contains the fix.
